Repository PratyayDhond/Kindle-Highlights-extractor, pull requests merged in 2023-10, with the labels that each got.

#1 Update README.md
  README.md
Labels: hacktoberfest

#3 Update README.md
  README.md
Labels: hacktoberfest

#5 Add CI/CD workflow to check code Formatting
  .github/workflows/lint.yml
  app.py
  scraper.py
Labels: hacktoberfest, hacktoberfest-accepted

#8 Add Github Action to autogenerate requirements
  .github/workflows/lint.yml
  .github/workflows/requirements.yml
  README.md
  requirements.txt
Labels: hacktoberfest, hacktoberfest-accepted

#10 Update requirements.txt
  requirements.txt
Labels: hacktoberfest, hacktoberfest-accepted

#11 Update Pipfile.lock
  Pipfile.lock
Labels: hacktoberfest, hacktoberfest-accepted

#14 Add dependabot config to keep dependencies updated
  .github/dependabot.yml
  __pycache__/app.cpython-310.pyc
  __pycache__/scraper.cpython-310.pyc
Labels: hacktoberfest-accepted

#16 Split the main download method into smaller fns
  .gitignore
  app.py
  scraper.py
Labels: hacktoberfest, hacktoberfest-accepted
